config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers:{
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get '/users/:id/edit', to: 'users#edit'
    patch '/user/:id', to: 'users/registrations#update'
    get 'addresses', to: 'users/registrations#new_address'
    get '/user_addresses/edit', to: 'users/registrations#edit_user_addresses'
    patch '/user_addresses/:id', to: 'users/registrations#update_user_addresses'
    post 'addresses', to: 'users/registrations#create_address'
    post '/user_addresses/:id', to: 'users/registrations#update_user_addresses'
  end
  root to: 'items#index'

  get 'items/purchase/:id', to: 'items#purchase'
  resources :items,only:[:action]
  resources :items do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    member do
      get 'purchase'
      post 'pay'
    end
  end

  resources :users ,only: [:show]
  resources :cards, only: [:new, :create, :show, :destroy] 
  resources :categories ,only: [:index,:show] 
end

app/views/shared/_card-show.html.haml
.card-show
  .card-show__fwrapper
    .card-show__fwrapper__title
      登録クレジット情報
    .card
      .card__info
        カード情報
        .card__info__numbers
          .number
            = "**** **** ****" + @customer_card.last4
        .expiration_date
          .expiration_date__title
            有効期限
          .expiration_date__info
            = @exp_month + " / " + @exp_year
      .edit__function
        = link_to "削除する", card_path, method: :delete, class: "destroy__function__btn"
    .payment-details
      = link_to "支払い方法について >", "", class: "payment-details__btn"

app/views/shared/_header.html.haml
.header
  .header__top
    .header__top__title
      = link_to image_tag("material/logo/logo.png", size: "170x50"),root_path
    .header__top__search
      %input.search-size{type: "text", placeholder: "キーワードから探す"}
    .header__top__search-image
      = image_tag "material/icon/icon-search 1.png", size: "25x25"
  .header__bottom
    .header__bottom__left
      .category
        .category__image
          = image_tag "material/icon/icon_category.png", size: "25x25"
        .category__text
          %nav#dd
            %ul.level0
              %li.position-setting
                %a{href: categories_path} カテゴリーから探す
                %ul.level1
                  - @parents.each do |parent|
                    %li
                      %a{href: category_path(parent.id)}
                        = parent.name
                      %ul.level2
                        - parent.children.each do |child|
                          %li
                            %a{href: category_path(child.id)} 
                              = child.name
                            %ul.level3
                              - child.children.each do |grandchild|
                                %li
                                  %a{href: category_path(grandchild.id)}
                                    = grandchild.name
                  %li
                    %a{href: categories_path}
                      カテゴリー一覧
      .brand
        .brand__image
          = image_tag "material/icon/icon_brand.png", size: "25x25"
        .brand__text
          %a{href:""}
            ブランドから探す
    .header__bottom__right
      - if user_signed_in?
        .user-name
          = link_to "#{current_user.nickname}さんのマイページ", user_path(current_user.id), class: "user-name-btn"
        .logout
          = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "logout-btn"
      - else
        .sign-up
          = link_to "新規登録", new_user_registration_path, class: "sign-up-btn"
        .login
          = link_to "ログイン", new_user_session_path, class: "login-btn"

  .breadcrumbs-frame
    = breadcrumbs pretext: "",separator: " &raquo; "

app/views/shared/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/shared/_side-bar.html.haml
.user-page__side
  - if @user == current_user
    .user-page__side__title
      マイページ
    %ul.user-page__side__contents
      %li.content
        = link_to root_path, class: "content-link" do
          .content-link__tag
            トップページ
          = icon("fas", "chevron-right", class: "right-icon")
      
      %li.content
        = link_to  new_item_path, class: "content-link" do
          .content-link__tag
            出品する
          = icon("fas", "chevron-right", class: "right-icon")

      %li.content
        = link_to  edit_user_registration_path, class: "content-link" do
          .content-link__tag
            本人情報変更
          = icon("fas", "chevron-right", class: "right-icon")

      %li.content
        = link_to new_card_path, class: "content-link" do
          .content-link__tag
            支払い情報変更
          = icon("fas", "chevron-right", class: "right-icon")

      %li.content
        = link_to user_addresses_edit_path, class: "content-link" do
          .content-link__tag
            発送・お届け先住所変更
          = icon("fas", "chevron-right", class: "right-icon")

  - else
    .user-page__side__title
      ="#{@user.nickname}さんのページ"
    %ul.user-page__side__contents
      %li.content
        = link_to root_path, class: "content-link" do
          .content-link__tag
            トップページ
          = icon("fas", "chevron-right", class: "right-icon")
          
      -if current_user
        %li.content
          = link_to user_path(current_user), class: "content-link" do
            .content-link__tag
              自分のマイページ
            = icon("fas", "chevron-right", class: "right-icon")

app/views/shared/_user-page-dummy-info.html.haml
= link_to "#", class: "info-card" do
  .info-card__img
    = image_tag "material/logo/mercari_profile.png", class: "master-img"
  .info-card__info
    .info-card__info__message
      本日限定！！ポイント５倍キャンペーン
    .info-card__info__date
      2020.07.12
  = icon("fas", "chevron-right", class: "right-icon")

= link_to "#", class: "info-card" do
  .info-card__img
    = image_tag "material/logo/mercari_profile.png", class: "master-img"
  .info-card__info
    .info-card__info__message
      本日限定！！ポイント５倍キャンペーン
    .info-card__info__date
      2020.07.12
  = icon("fas", "chevron-right", class: "right-icon")

= link_to "#", class: "info-card" do
  .info-card__img
    = image_tag "material/logo/mercari_profile.png", class: "master-img"
  .info-card__info
    .info-card__info__message
      本日限定！！ポイント５倍キャンペーン
    .info-card__info__date
      2020.07.12
  = icon("fas", "chevron-right", class: "right-icon")  

= link_to "#", class: "info-card" do
  .info-card__img
    = image_tag "material/logo/mercari_profile.png", class: "master-img"
  .info-card__info
    .info-card__info__message
      本日限定！！ポイント５倍キャンペーン
    .info-card__info__date
      2020.07.12
  = icon("fas", "chevron-right", class: "right-icon")

= link_to "#", class: "info-card" do
  .info-card__img
    = image_tag "material/logo/mercari_profile.png", class: "master-img"
  .info-card__info
    .info-card__info__message
      本日限定！！ポイント５倍キャンペーン
    .info-card__info__date
      2020.07.12
  = icon("fas", "chevron-right", class: "right-icon")

app/views/shared/_user-page-nothing-img.html.haml
.nothing
  = image_tag "material/logo/logo.png", class: "nothing__img"
  .nothing__nothing-text
    現在、やることはありません。

app/views/shared/_user_show_item.html.haml
- items.each do |item|
  .user-items-data
    .user-items-data__image
      =image_tag item.images[0].image.url, size: '70×70'
    .user-items-data__flex
      .items-name
        =link_to "#{item.item_name}", item_path(item)
      .items-price
        %p
          ="#{item.price}円"
    .user-items-data__status
      -if item.status == true
        %p{class:"status-true"} 出品中
      -else
        %p{class:"status-false"} 売却済 