config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers:{
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get '/users/:id/edit', to: 'users#edit'
    patch '/user/:id', to: 'users/registrations#update'
    get 'addresses', to: 'users/registrations#new_address'
    get '/user_addresses/edit', to: 'users/registrations#edit_user_addresses'
    patch '/user_addresses/:id', to: 'users/registrations#update_user_addresses'
    post 'addresses', to: 'users/registrations#create_address'
    post '/user_addresses/:id', to: 'users/registrations#update_user_addresses'
  end
  root to: 'items#index'

  get 'items/purchase/:id', to: 'items#purchase'
  resources :items,only:[:action]
  resources :items do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    member do
      get 'purchase'
      post 'pay'
    end
  end

  resources :users ,only: [:show]
  resources :cards, only: [:new, :create, :show, :destroy] 
  resources :categories ,only: [:index,:show] 
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :user
  belongs_to :category
  belongs_to_active_hash :condition
  belongs_to_active_hash :delivery_fee
  belongs_to_active_hash :ship_date
  belongs_to_active_hash :brand
  has_many :images
  has_one :trade
  accepts_nested_attributes_for :images, allow_destroy: true

  validates :item_name, :explanation,:price,:condition,:ship_date,:delivery_fee,  presence: true
  validates :images, length: { minimum: 1, maximum: 10 }
  validates :price,numericality: {only_integer: true, greater_than_or_equal_to: 300, less_than_or_equal_to: 9999999}

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, except: [:index, :new, :create, :get_category_children, :get_category_grandchildren, :purchase, :pay]
  before_action :check_login_user, except: [:index, :show, :purchase, :pay]
  before_action :check_correct_user, only: [:edit, :update, :destroy]
  before_action :set_caegory_for_new_create, only: [:new, :create]
  before_action :set_user_addresses, only: [:new, :create,:edit, :update, :destroy]
  before_action :set_category_for_edit_update, only: [:edit, :update]
  
  def index
    @categories=Category.where(ancestry: nil)
  end

  def new
    @item = Item.new
    @images = @item.images.build
  end

  def get_category_children
    @category_children = Category.find_by(name: "#{params[:parent_name]}", ancestry: nil).children
  end

  def get_category_grandchildren
    @category_grandchildren = Category.find("#{params[:child_id]}").children
  end
  
  def create
    @item = Item.create(items_params)
    if @item.save
      flash[:notice] = "出品しました"
      redirect_to root_path
    else
      flash.now[:alert] = "内容を確認してください"
      @images = @item.images.build
      render new_item_path
    end
  end
  
  def show
    @categories = Category.find(@item.category_id)
    @categories2 = @categories.parent
    
  end
  
  def edit
    @images = @item.images
  end
  
  def update
    if @item.update(items_params)
      flash[:notice] = "内容を更新しました"
      redirect_to root_path
    else
      flash.now[:alert] = "編集内容を確認してください"
      @images = @item.images
      render :edit
    end
  end

  def destroy
    if @item.destroy
      flash[:notice] = "出品を取り消しました"
      redirect_to root_path
    else
      flash[:alert] = "取り消しに失敗しました"
      render :edit
    end
  end

  def purchase
    unless user_signed_in?
      redirect_to new_user_session_path
    else
      @item = Item.find(params[:id])
      @trade = Trade.new
      @card = Card.find_by(user_id: current_user.id)

      unless @card.blank?
        Payjp.api_key = Rails.application.credentials[:payjp][:PAYJP_SECRET_KEY]
        customer = Payjp::Customer.retrieve(@card.customer_id)
        @customer_card = customer.cards.retrieve(@card.card_id)
        @exp_month = @customer_card.exp_month.to_s
        @exp_year = @customer_card.exp_year.to_s.slice(2..4)
      end
    end
  end

  def pay
    @item = Item.find(params[:id])
    @image = @item.images.first
    @item.update(status: false)
    @user = current_user
    Trade.create(create_params)

    @item.with_lock do
      if current_user.card.present?
        @card = Card.find_by(user_id: @user.id)
        Payjp.api_key = Rails.application.credentials[:payjp][:PAYJP_SECRET_KEY] 
        charge = Payjp::Charge.create(
        amount: @item.price,
        customer: Payjp::Customer.retrieve(@card.customer_id),
        currency: 'jpy'
        )
      else
        Payjp::charge.create(
        amount: @item.price,
        card: params['payjp-token'],
        currency: 'jpy'
        )
      end 
    end
  end

  private
    def items_params
      params.require(:item).permit(:item_name, :explanation, :price, :brand_id, :condition_id, :ship_date_id, :delivery_fee_id,:category_id,:user_address_id,images_attributes: [:image,:_destroy, :id]).merge(user_id: current_user.id )
    end

    def set_item
      @item = Item.find(params[:id])
    end

    def set_caegory_for_new_create
      @category_parent_array = ["---"] + Category.where(ancestry: nil).first(13).pluck(:name)
    end
    
    def set_user_addresses
      @user_address = UserAddress.where(user_id: current_user.id)
      @addresses = [] 
      @user_address.each do |user_address|
        address = ["〒#{user_address.post}" + "  /  " + "#{user_address.preficture}" + "#{user_address.city}" + "#{user_address.block}" + "#{user_address.building}", "#{user_address.id}"]
        @addresses << address
      end
    end

    def set_category_for_edit_update
      @category_grandchildren = Category.find(@item[:category_id])
      @category_children = @category_grandchildren.parent
      @category_parent_array =  ["#{@category_children.parent.name}"] + Category.where(ancestry: nil).first(13).pluck(:name)
      @current_item_category = "#{@category_children.parent.name}/#{@category_children.name}/#{@category_grandchildren.name}"
    end

    def check_login_user
      unless current_user
        flash[:alert] = "アクセス権限がありません"
        redirect_to root_path
      end
    end

    def check_correct_user
      unless @user = current_user
        flash[:alert] = "アクセス権限がありません"
        redirect_to root_path
      end
    end

    def create_params
      params.require(:trade).permit(:item_id, :buyer_id, :seller_id)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.haml
.put-item-page
  .put-item-page__topimage
    = link_to root_path do
      = image_tag "material/logo/logo.png", height: "50px", width: "200px"
  =form_with model: @item, local: true do |f|
    .put-item-page__form
      =render "items/items_error_list", {item: @item}
      .form-data
        .form-data__item.form-data__image
          .form-title
            %label 出品画像
            .form-title__required
              %label 必須
          .form-condition
            %p 最大10枚までアップロードできます
          #previews
            -if @item.persisted? 
              -@item.images.each_with_index do |image, i| 
                =image_tag image.image.url, data: { index: i }, width: "100", height: '100' 
          .form-input-image
            = f.fields_for :images, @images do |img|
              %div{"data-index": "#{img.index}" ,class:"js-file_group"}
                %label{"data-index": "#{img.index}" }
                  =img.file_field :image, class: 'js-file'
                  %span
                    = "#{img.index + 1}: 画像選択"
                %span{class:"js-remove"}
                  削除
              - if @item.persisted?
                = img.check_box :_destroy, data:{ index: img.index }, class: 'hidden-destroy', checked: false
            - if @item.persisted? 
              %div{"data-index": "#{@item.images.count}", class:"js-file_group"}
                %label{"data-index": "#{@item.images.count}" }
                  = file_field_tag :image, name: "item[images_attributes][#{@item.images.count}][image]",id: "item_images_attributes_#{@item.images.count}_id", class: 'js-file' 
                  %span
                    = "#{@item.images.count + 1}: 画像選択"
                %span{class:"js-remove"}
                  削除

        .form-data__item
          .form-title
            =f.label "商品名"
            .form-title__required
              %label 必須
          .form-input-text
            =f.text_field :item_name, placeholder: "商品名を入力してください"
          .form-title
            =f.label "商品説明"
            .form-title__required
              %label 必須
          .form-input-textarea
            =f.text_area :explanation, placeholder: "商品の説明\n(色、素材、定価など)\n\n例）2010年ごろ購入したセーターです。ライトグレーで、目立った傷や汚れはございません。"

        .form-data__item
          .form-group
            %label 商品詳細
          .form-title
            =f.label "カテゴリ"
            .form-title__required
              %label 必須
          .form-input-select
            - if @item.persisted?
              %p
                = "#{@current_item_category}"
            = f.select :category_id3, @category_parent_array, {}, {class: 'listing-select-wrapper__box--select', id: 'parent_category'}
          .listing-product-detail__category

          .form-title
            =f.label "ブランド"
            .form-title__any
              %label 任意
          .form-input-select
            =f.collection_select :brand_id, Brand.all, :id, :brand, include_blank: "選択してください"
          .form-title
            =f.label "商品の状態"
            .form-title__required
              %label 必須
          .form-input-select
            =f.collection_select :condition_id, Condition.all, :id, :condition, include_blank: "選択してください"

        .form-data__item
          .form-group
            %label 配送について
          .form-title
            %label 配送元の地域
          .form-input-select 
            =f.select :user_address_id, @addresses,include_blank: "選択してください"  
          .form-title
            =f.label "発送までの日数"
            .form-title__required
              %label 必須
          .form-input-select
            =f.collection_select :ship_date_id, ShipDate.all, :id, :ship_date, include_blank: "選択してください"
          .form-title
            =f.label "配送料の負担について"
            .form-title__required
              %label 必須
          .form-input-select
            =f.collection_select :delivery_fee_id, DeliveryFee.all, :id, :delivery_fee, include_blank: "選択してください"

            
        .form-data__item.form-data__price
          .form-group
            %label 価格(¥300 ~9,999,999)
          .form-price-flex
            .form-title
              =f.label "販売価格"
              .form-title__required
                %label 必須
            =f.number_field :price
        .form-data__submit
          =f.submit value: "出品する"
        =@categories
        - if @item.persisted?
          .form-data__delete
            =link_to "出品を取り消す",  item_path(@item), method: :delete, data: { confirm: "削除してよろしいですか？"}
=@a

app/views/items/_items_error_list.html.haml
-if item.errors.any?
  #errors_list
    %p
      = pluralize(item.errors.count, "error")
    %ul
      -item.errors.full_messages.each do |error|
        %li
          = error

app/views/items/_senditem.html.haml
=link_to new_item_url do
  .senditem
    出品する
    .senditem__image
      =image_tag "material/icon1/camera.svg",class:"senditem__image"

app/views/items/edit.html.haml
= render 'items/form'

app/views/items/index.html.haml
= render "shared/header"

- unless user_signed_in?
  .contents1 
    .contents1--image
      =image_tag "material/pict/bg-mainVisual-pict_pc.jpg",class:"top-image"
      .contents1--image__text1
        人生を変えるフリマアプリ
      .contents1--image__text2
        FURIMAはだれでもかんたんに出品・購入できる
        %br フリマアプリです
      .contents1--image__image
        =link_to "#",class: 'link' do
          .contents1--image__image--1
            =image_tag "material/icon1/Apple Button.svg",class:"contents1--image__image--1"
        =link_to "#",class: 'link' do
          .contents1--image__image--2    
            =image_tag "material/icon1/Google Button.svg",class:"contents1--image__image--2"

  .contents2
    .contents2__top
      FURIMAが選ばれる３つの理由
      -# .contents2__top--bottom
    .contents2__bottom
      .contents2__bottom__left
        .contents2__bottom__left--top
          =image_tag "material/pict/pict-reason-01.jpg",class:"contents2-image",size: '150×150'
        .contents2__bottom__left--bottom
          %span<> 3分で   
          すぐに出品できる！
        
      .contents2__bottom__middle
        .contents2__bottom__middle--top
          =image_tag "material/pict/pict-reason-02.jpg",class:"contents2-image"
        .contents2__bottom__middle--bottom
          %span<> シンプル 
          で使いやすい !
      .contents2__bottom__right
        .contents2__bottom__right--top
          =image_tag "material/pict/pict-reason-03.jpg",class:"contents2-image"
        .contents2__bottom__right--bottom
          %span<> 手数料 
          業界最安 !

  .contents3
    =image_tag "material/pict/bg-topMiddleDl-pict.jpg",class:"contents3-image"
    .contents3__image
    .contents3__top
      %h 会員数日本一位
    .contents3__middle
      %h FURIMAは、フリマアプリで最も人気。
      %br 出品・購入回数も業界最多です！
      ほしかったあの商品に出会えるかもしれません。
    .contents3__bottom
      .contents3__bottom--left
        =link_to "#" do
          =image_tag "material/icon1/Apple Button.svg",class:"contents3__bottom--left"
      .contents3__bottom--right
        =link_to "#" do
          =image_tag "material/icon1/Google Button.svg",class:"contents3__bottom--right"

  .contents4
    .contents4__top
      %h FURIMAの特徴
      .contents4__top--bottom
    .contents4__bottom
      .contents4__bottom__left
        .contents4__bottom__left--top
          =image_tag "material/icon/icon-01.png",class:"contents4__bottom__left--top"
        .contents4__bottom__left--bottom
          %h 簡単に売り買いできる
      .contents4__bottom__middle
        .contents4__bottom__middle--top
          =image_tag "material/icon/icon-03.png",class:"contents4__bottom__middle--top"
        .contents4__bottom__middle--bottom
          %h 売上金は即日振込みに対応
      .contents4__bottom__right
        .contents4__bottom__right--top
          =image_tag "material/icon/icon-04.png",size: "306×306",class:"contents4-image"
        .contents4__bottom__right--bottom
          %h 様々な支払いに対応

- if user_signed_in?
  .top_image_after_login
    = image_tag "material/logo/after-login.jpg", height: '300px', width: '100%'
.top_message_after_login
  %h2 カテゴリ別新着商品

.category-items
  - @categories.each do |category|
    .contents 
      .contents--category
        =link_to category_path(category.id),class:'category_name' do
          ="#{category.name}新着アイテム"
      .contents--goods
        .contents--goods--list 
          - @goods_list=(Item.where(category_id: category.id )).or(Item.where(category_id:category.child_ids)).or(Item.where(category_id: category.indirect_ids)).order("created_at DESC")
          -@goods = @goods_list.where(status: 1).limit(5)
          - @goods.each do |item|
            - if item.status==true then
              .list1
                =link_to item_path(item.id) ,class:'button1'do
                  .list1--top
                    -item.images.each do |image|
                      =image_tag image.image.url,size:'200x200'
                      - break
                  .list1--bottom
                    =item.item_name 
                  .list1--bottom--price
                    ="#{item.price}円" 

.contents18
  =image_tag "material/pict/bg-topMiddleDl-pict.jpg",class:"contents18"
  .contents18--top
    だれでもかんたん、人生を変えるフリマアプリ
  .contents18--middle
    今すぐ無料ダウンロード！
  .contents18--bottom
    =link_to '#' do
      .contents18--bottom--left
        =image_tag "material/icon1/Apple Button.svg",class:"contents18--bottom--left"
    =link_to '#' do
      .contents18--bottom--right
        =image_tag "material/icon1/Google Button.svg",class:"contents18--bottom--right"
  .contents19
  .contents19--image
    =image_tag "material/logo/logo-white.png",class:"contents19--image"
=render "items/senditem"

app/views/items/new.html.haml
= render 'items/form'

app/views/items/pay.html.haml
.pay
  .account-page__topimage
    = image_tag "material/logo/logo.png",height: "50px", width: "200px"
  .main_contents
    .main_details
      .main_details__message
        購入が完了しました。
      .main_details__check
        購入内容の確認
    .main_contents__wrapper
      .main_contents__wrapper__picture
        = image_tag @image.image.url, alt: "商品イメージ", class: "item-image",size: '120x120'

      .main_contents__wrapper__item
        = @item.item_name
        = @item.price
        %br 円

    %ul.purchased__links
      %li.purchased__links__TopPage
        = link_to "トップページに戻る", root_path, class: "purchased__links__TopPage__btn"
      %li.purchased__links__index
        = link_to "マイページに戻る", user_path(current_user), class: "purchased__links__index__btn"

app/views/items/purchase.html.haml
.single 
  .single__container
    .single__container--header
      = link_to root_path do
        = image_tag "material/logo/logo.png", size:"170x50"
    .single__container--contents
      .single__container--contents__checkpage
        .single__container--contents__checkpage--1
          購入内容の確認
        .single__container--contents__checkpage--2
          .single__container--contents__checkpage--2__image
            -@item.images.each do |image|
              =image_tag image.image.url,size:'200x200'
              - break
          .single__container--contents__checkpage--2__name
            .name
              =@item.item_name
            .explanation
              =safe_join(@item.explanation.split("\n"), tag(:br))
        .single__container--contents__checkpage--3
          .single__container--contents__checkpage--3__fee
            %span.single__container--contents__checkpage--3__fee--1
              %h 支払い金額：
            %span.single__container--contents__checkpage--3__fee--yen
              =@item.price
              円
        .pay-method
          -if @card.blank? 
            .pay-method__title
              支払い方法
            .pay-method__card
              =link_to "支払い方法が未設定です。", "/cards/new",class: "pay-method__card__add"
          -else 
            =render "shared/card-show"

        .ship-address
          .ship-address__title
            .title-main
              配送先
          .ship-address__adress
            =current_user.user_address.preficture
            =current_user.user_address.city
            =current_user.user_address.block 
            =current_user.user_address.building
          =link_to "[変更する]", "/user_addresses/edit", method: :get, class: "ship-address__edit"

        .single__container--contents__checkpage--3__btn2
          .btn-buy
            - if @card.blank?
              =link_to "クレジットカードを登録する", "/cards/new", class:"purchase-btn"
            - else
              = form_with model: @trade, url: "/items/#{@item.id}/pay", method: :post, local: true do |f|
                = f.hidden_field :item_id, :value => @item.id
                = f.hidden_field :buyer_id, :value => @item.user_id
                = f.hidden_field :seller_id, :value => current_user.id
                = f.submit "購入する", class: "purchase-btn",data: { confirm: "購入でよろしいですか？"}

  .single__container--footer 
    .single__container--footer__clearfix
      =link_to "#",class: 'btn-1' do
        プライバシーポリシーについて
      =link_to "#" ,class: 'btn-2' do
        FURIMA利用規約について
      =link_to "#" ,class: 'btn-3' do
        特定商取引に関する表記について
      .single__container--footer__clearfix--image

app/views/items/show.html.haml
= render "shared/header"

.item-show-page
  .item-show-main
    .item-show-main__item-name
      %h1
        = @item.item_name
    .item-show-main__item-detail
      .item-show-main__item-detail__images
        .slides
          - @item.images.each do |image|
            %ul
              %li
                = image_tag image.image.to_s, size: "300x300"
      .item-show-main__item-detail__item-info
        %table.item-info-table
          %tr
            %th 出品者
            %td 
              = link_to "#{@item.user.nickname}", user_path(@item.user)
          %tr
            %th カテゴリー
            %td 
              %ul
                - if @categories2.has_parent?
                  %li

                    = link_to category_path(@categories2.parent.id) do
                      = @categories2.parent.name
                  %li
                    = link_to category_path(@categories2.id) do
                      = icon("fas", "angle-right")
                      = @categories2.name
                  %li
                    = link_to category_path(@categories.id) do
                      = icon("fas", "angle-double-right")
                      = @categories.name
                - else
                  %li
                    = link_to category_path(@categories2) do
                      = @categories2.name
                  %li
                    = link_to category_path(@categories) do
                      = icon("fas", "angle-right")
                      = @categories.name
          %tr
            %th ブランド
            %td 
              -if @item.brand.present?
                = @item.brand.brand
          %tr
            %th 商品の状態
            %td 
              = @item.condition.condition
          %tr
            %th 配送料の負担
            %td 
              = @item.delivery_fee.delivery_fee
          %tr
            %th 配送元地域
            %td 
              = @item.user.user_address.preficture
          %tr
            %th 発送日の目安
            %td 
              = @item.ship_date.ship_date

    .item-show-main__price-box
      %span.item-price
        = "¥#{@item.price}"
      %span.item-tax (税込)
      %span.item-delivery-fee
        = @item.delivery_fee.delivery_fee
    - unless user_signed_in? && current_user.id == @item.user_id then
      .item-show-main__purchase
        = link_to "購入画面に進む",  purchase_item_path(@item),  class: "item-purchase-btn"
    .item-show-main__explanation
      =simple_format @item.explanation
  - if user_signed_in? && current_user.id == @item.user_id then
    .item-show-btn
      = link_to "商品の編集", edit_item_path(@item),  class: "item-edit-btn"
      %p or
      = link_to "この商品を削除する", item_path(@item), method: :delete, class: "item-destroy-btn",data: { confirm: "削除してよろしいですか？"}