config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers:{
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get '/users/:id/edit', to: 'users#edit'
    patch '/user/:id', to: 'users/registrations#update'
    get 'addresses', to: 'users/registrations#new_address'
    get '/user_addresses/edit', to: 'users/registrations#edit_user_addresses'
    patch '/user_addresses/:id', to: 'users/registrations#update_user_addresses'
    post 'addresses', to: 'users/registrations#create_address'
    post '/user_addresses/:id', to: 'users/registrations#update_user_addresses'
  end
  root to: 'items#index'

  get 'items/purchase/:id', to: 'items#purchase'
  resources :items,only:[:action]
  resources :items do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    member do
      get 'purchase'
      post 'pay'
    end
  end

  resources :users ,only: [:show]
  resources :cards, only: [:new, :create, :show, :destroy] 
  resources :categories ,only: [:index,:show] 
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  require "payjp"

  def new
    @card = Card.where(user_id: current_user.id)
    redirect_to card_path(current_user.id) if @card.exists?
  end

  def create
    Payjp.api_key = Rails.application.credentials[:payjp][:PAYJP_SECRET_KEY] 

    if params["payjp_token"].blank?
      redirect_to action: "new", alert: "クレジットカードを登録できませんでした。"
    else
      customer = Payjp::Customer.create(
        email: current_user.email,
        card: params["payjp_token"],
        metadata: {user_id: current_user.id}
      )
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)

      if @card.save
        redirect_to root_path, nortice: "カード情報を登録しました。"
      else
        redirect_to action: "create"
      end
    end
  end

  def show
    @card = Card.find_by(user_id: current_user.id)
    if @card.blank?
      redirect_to action: "new"
    else
      Payjp.api_key = Rails.application.credentials[:payjp][:PAYJP_SECRET_KEY] 
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @customer_card = customer.cards.retrieve(@card.card_id)
      @exp_month = @customer_card.exp_month.to_s
      @exp_year = @customer_card.exp_year.to_s.slice(2..4)
    end
  end

  def destroy
    @card = Card.find_by(user_id: current_user.id)
    if @card.blank?
      redirect_to action: "new"
    else
      Payjp.api_key = Rails.application.credentials[:payjp][:PAYJP_SECRET_KEY] 
      customer = Payjp::Customer.retrieve(@card.customer_id)
      customer.delete
      @card.delete

      if @card.destroy
        redirect_back fallback_location: root_path, alert: "カード情報を削除しました。"
      else
        redirect_to card_path(current_user.id), alert: "削除できませんでした。"
      end
    end
  end
end

app/helpers/card_helper.rb
module CardHelper
end

app/views/cards/new.html.haml
.card_add 
  .card_add__topimage
    = image_tag "material/logo/logo.png",height: "50px", width: "200px"
  .card_add__form
    .title 支払い方法
    = form_with model: @card, url: cards_path, method: :post, html:{ id: "charge-form", class: "details", name: "inputForm" } do |f|
      .number-details
        .card-number カード番号
        %span.must_check 必須
      .number
        = f.text_field 'payment_card_no', class: 'cardnumber', id: "payment_card_no", placeholder: '半角数字のみ', type: "text", maxlength: "16"
      .image
        = image_tag(image_path('material/cards/visa.png'), class: 'visa')
        = image_tag(image_path('material/cards/master.png'), class: 'master')
        = image_tag(image_path('material/cards/jcb.png'), class: 'jcb')
        = image_tag(image_path('material/cards/amex.png'), class: 'amex')
        = image_tag(image_path('material/cards/diners.png'), class: 'diners')
        = image_tag(image_path('material/cards/discover.png'), class: 'discover')

      .expirationdate
        .expirationdate__details
          .date 有効期限
          %span.must_check 必須
        .expirationdate__choice
          .month
            %select#payment_card_month.card-default{name: "payment_card_month", type: "text"}
              %option{value: "1"} 01
              %option{value: "2"} 02
              %option{value: "3"} 03
              %option{value: "4"} 04
              %option{value: "5"} 05
              %option{value: "6"} 06
              %option{value: "7"} 07
              %option{value: "8"} 08
              %option{value: "9"} 09
              %option{value: "10"} 10
              %option{value: "11"} 11
              %option{value: "12"} 12
          .month-details 月
          .year
            %select#payment_card_year.card-default{name: "payment_card_year", type: "text"}
              %option{value: "2020"} 20
              %option{value: "2021"} 21
              %option{value: "2022"} 22
              %option{value: "2023"} 23
              %option{value: "2024"} 24
              %option{value: "2025"} 25
              %option{value: "2026"} 26
              %option{value: "2027"} 27
              %option{value: "2028"} 28
              %option{value: "2029"} 29
              %option{value: "2030"} 30
          .year-details 年

      .securitycode
        .securitycode__details
          .securitycode-details__title セキュリティコード
          %span.must_check 必須
        .securitycode__cardsecurity
          = f.text_field "payment_card_cvc", type: 'text', class: 'securitycode__cardsecurity__form', id: "payment_card_cvc", maxlength: "4", placeholder: 'カード背面4桁もしくは3桁の番号'
          .card-question カード裏面の番号とは？
      .add 
        = f.submit "登録する", class: "add__btn", id: "token_submit"

app/views/cards/show.html.haml
.card-show-page
  .card_add__topimage
    = link_to root_path do
      = image_tag "material/logo/logo.png",height: "50px", width: "200px"
  =render "shared/card-show"